name: Sync GitLab to GitHub

on:
  schedule:
    - cron: '0 0 * * *' # 每天运行一次，你可以根据需要调整时间
  workflow_dispatch: # 手动触发工作流

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Set up Git
      env:
        MY_EMAIL: ${{ secrets.MY_EMAIL }}
        MY_USERNAME: ${{ secrets.MY_USERNAME }}
      run: |
        git config --global user.name "${MY_USERNAME}"
        git config --global user.email "${MY_EMAIL}"

    - name: Clone GitLab repo
      env:
        GITLAB_REPO: https://gitlab.com/exploit-database/exploitdb.git
        GITHUB_REPO: exploitdb
      run: |
        git clone $GITLAB_REPO $GITHUB_REPO
        cd $GITHUB_REPO

    - name: Add GitHub remote
      env:
        GITHUB_REPO: exploitdb
        MY_USERNAME: ${{ secrets.MY_USERNAME }}
      run: |
        cd $GITHUB_REPO
        git remote add github https://github.com/${MY_USERNAME}/$GITHUB_REPO.git
        git fetch github

    - name: Pull from GitHub and merge
      env:
        GITHUB_REPO: exploitdb
      run: |
        cd $GITHUB_REPO
        git pull github main

    - name: Push to GitHub
      env:
        GITHUB_REPO: exploitdb
      run: |
        cd $GITHUB_REPO
        git push github main

    - name: Clean up
      env:
        GITHUB_REPO: exploitdb
      run: rm -rf $GITHUB_REPO
