name: Sync GitLab to GitHub

on:
  schedule:
    - cron: '0 0 * * *' # 每天运行一次，你可以根据需要调整时间
  workflow_dispatch: # 手动触发工作流

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        ref: main

    - name: Set up Git
      run: |
        git config --global user.name "offsoc"
        git config --global user.email "liguofeng@boprin.onmicrosoft.com"

    - name: Clone GitLab repo
      run: |
        git clone https://gitlab.com/exploit-database/exploitdb.git
        cd exploitdb

    - name: Add GitHub remote
      run: |
        cd exploitdb
        git remote add github https://github.com/${{ github.repository }}.git
        git fetch github

    - name: Pull from GitHub and merge
      run: |
        cd exploitdb
        git pull github main

    - name: Push to GitHub
      run: |
        cd exploitdb
        git push github main

    - name: Clean up
      run: rm -rf exploitdb
