name: Sync from upstream

on:
  schedule:
    - cron: '0 0 * * *'  # 每天0点运行一次
  workflow_dispatch:  # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false  # 禁用自动拥有的GitHub token
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name 'YOUR_GITHUB_USERNAME'
          git config user.email 'YOUR_GITHUB_EMAIL'

      - name: Add upstream remote
        # 添加上游远程仓库
        run: git remote add upstream https://gitlab.com/exploit-database/exploitdb.git

      - name: Fetch upstream
        # 获取上游所有分支
        run: git fetch upstream

      - name: Merge upstream changes
        # 合并上游主分支更改到当前分支（假设当前分支为master，如果是main，请替换为main）
        run: git merge upstream/master --allow-unrelated-histories

      - name: Push changes
        # 推送更改到GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin master
