name: Sync GitLab to GitHub

on:
  schedule:
    - cron: '0 0 * * *' # 每天运行一次，你可以根据需要调整时间
  workflow_dispatch: # 手动触发工作流

env:
  GITLAB_REPO: https://gitlab.com/exploit-database/exploitdb.git
  GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
  GITHUB_EMAIL: ${{ secrets.GITHUB_EMAIL }}
  GITHUB_REPO: exploitdb
  GITHUB_URL: https://github.com/${{ secrets.GITHUB_USERNAME }}/${{ env.GITHUB_REPO }}.git

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        ref: main

    - name: Set up Git
      run: |
        git config --global user.name "${{ env.GITHUB_USERNAME }}"
        git config --global user.email "${{ env.GITHUB_EMAIL }}"

    - name: Clone GitLab repo
      run: |
        git clone ${{ env.GITLAB_REPO }} ${{ env.GITHUB_REPO }}
        cd ${{ env.GITHUB_REPO }}

    - name: Add GitHub remote
      run: |
        cd ${{ env.GITHUB_REPO }}
        git remote add github ${{ env.GITHUB_URL }}
        git fetch github

    - name: Pull from GitHub and merge
      run: |
        cd ${{ env.GITHUB_REPO }}
        git pull github main

    - name: Push to GitHub
      run: |
        cd ${{ env.GITHUB_REPO }}
        git push github main

    - name: Clean up
      run: rm -rf ${{ env.GITHUB_REPO }}
